/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef HS485DEMO_PRIVATE_H
#define HS485DEMO_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.6.1.91"
#define VER_MAJOR	1
#define VER_MINOR	6
#define VER_RELEASE	1
#define VER_BUILD	91
#define COMPANY_NAME	"ELV Elektronik EG"
#define FILE_VERSION	"1.6.1.42"
#define FILE_DESCRIPTION	"Demo -Software HS485"
#define INTERNAL_NAME	"HS485Demo.exe"
#define LEGAL_COPYRIGHT	"(C) 2005 - ELV Elektronik AG"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"HS485Demo.exe"
#define PRODUCT_NAME	"ELV HS485 Demo-Software"
#define PRODUCT_VERSION	"V1.60"

#endif /*HS485DEMO_PRIVATE_H*/
